[package]
name = "algosul_blog"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1"

[dependencies.web-sys]
version = "0.3"
features = ["Window", "Performance", "PerformanceTiming"]

[profile.release]
opt-level = "z"   # 优化大小
lto = true        # 链接时优化
strip = true      # 去除符号
codegen-units = 1 # 单一代码生成单元以提高优化效果
